// Generated by scripts/gen-voiceover.mjs — do not edit by hand.
// Measured mp3 durations in seconds, before VO_RATE playback scaling.
// Regenerate: npm run voiceover -- scripts/voiceover/yoloco-audience-fit.json --durations-only
export const DURATIONS = {
  "01-hook": 3.437,
  "02-creator": 5.016,
  "03-vanity": 2.276,
  "04-matters": 5.387,
  "05-versus": 4.18,
  "06-cta": 2.74,
  "07-brand": 3.204,
} as const;
