// Generated by scripts/gen-voiceover.mjs — do not edit by hand.
// Measured mp3 durations in seconds, before VO_RATE playback scaling.
// Regenerate: npm run voiceover -- scripts/voiceover/yoloco-explorer-ru.json --durations-only
export const DURATIONS = {
  "01-hook": 10.08,
  "02-prompt": 9.12,
  "03-results": 9.84,
  "04-pick": 7.28,
  "05-more": 5.68,
  "06-export": 4.56,
  "07-cta": 4.56,
} as const;
