// Generated by scripts/gen-voiceover.mjs — do not edit by hand.
// Measured mp3 durations in seconds, before VO_RATE playback scaling.
// Regenerate: npm run voiceover -- scripts/voiceover/yoloco-explorer.json --durations-only
export const DURATIONS = {
  "01-hook": 10.96,
  "02-prompt": 9.44,
  "03-results": 10.64,
  "04-pick": 7.12,
  "05-more": 6.4,
  "06-export": 6.4,
  "07-cta": 4.4,
} as const;
