// Generated by scripts/gen-voiceover.mjs — do not edit by hand.
// Measured mp3 durations in seconds, before VO_RATE playback scaling.
// Regenerate: npm run voiceover -- scripts/voiceover/secret-model.json --durations-only
export const DURATIONS = {
  "01-hook": 4.458,
  "02-internal": 2.137,
  "03-ladder": 5.248,
  "04-testing": 4.876,
  "05-pipeline": 4.783,
  "06-gap": 4.365,
  "07-law": 1.579,
} as const;
