// Generated by scripts/gen-voiceover.mjs — do not edit by hand.
// Empty until the voiceover is synthesised:
//   npm run voiceover -- scripts/voiceover/dubai-economy.json
export const DURATIONS = {} as Record<string, number>;
