// Generated by scripts/gen-voiceover.mjs — do not edit by hand.
// Measured mp3 durations in seconds, before VO_RATE playback scaling.
// Regenerate: npm run voiceover -- scripts/voiceover/dubai-economy.json --durations-only
export const DURATIONS = {
  "01-hook": 5.184,
  "02-turn": 7.008,
  "03-oil": 8.304,
  "04-port": 7.656,
  "05-map": 5.328,
  "06-airport": 5.568,
  "07-tax": 5.568,
  "08-model": 7.008,
  "09-crisis": 6.576,
  "10-rescue": 7.32,
  "11-answer": 5.136,
  "12-cta": 3.648,
} as const;
