// Generated by scripts/gen-footage.mjs — do not edit by hand.
// Measured after the cut, not copied from the config: the config asks for a
// range, ffmpeg delivers whole frames, and the two differ by up to one frame.
// Regenerate: node scripts/gen-footage.mjs scripts/footage/dubai-economy.json
export const FOOTAGE = {
  "06-airport-a380": { seconds: 6.533, width: 1080, height: 608 }, // «Эмирейтс» и аэропорт Дубая: A380 в ливрее Emirates на рулёжке DXB
  "05-map-takeoff": { seconds: 3, width: 1080, height: 608 }, // «за восемь часов полёта отсюда»: взлёт над Дубаем из окна (текстура, ≤2 с)
} as const;

/** Every clip is cut to this rate; a scene may assume it. */
export const FOOTAGE_FPS = 30;

export type FootageShot = keyof typeof FOOTAGE;
