// Generated by scripts/gen-heygen.mjs — do not edit by hand.
// Presenter shots: where each talking-head insert lands in the reel and
// how long the generated file actually is (measured, at 1.0x — play it at
// VO_RATE like the voiceover track, and keep it muted: the audio already
// comes from public/voiceover/dubai-economy/.
// enabled:false shots are still cut (the concat offsets depend on them)
// but are not rendered — see "_disabled" in the manifest for why.
// Regenerate: npm run heygen -- scripts/presenter/dubai-economy.json
export const PRESENTER = {
  "p1-hook": { clip: "01-hook", style: "fullbleed", reelIn: 0, duration: 3.28, file: "p1-hook.mp4", enabled: true },
} as const;
