// Generated by scripts/gen-voiceover.mjs — do not edit by hand.
// Measured mp3 durations in seconds, before VO_RATE playback scaling.
// Regenerate: npm run voiceover -- scripts/voiceover/audience-overlap.json --durations-only
export const DURATIONS = {
  "01-hook": 5.851,
  "02-overlap": 3.808,
  "03-reach": 4.551,
  "04-tax": 4.226,
  "05-yoloco": 6.548,
  "06-question": 4.273,
} as const;
