// Generated by scripts/gen-source-cut.mjs — do not edit by hand.
// Regenerate: node scripts/gen-source-cut.mjs scripts/cuts/unicorn-cafe.json
//
// BEATS are scene lengths in seconds, measured off the source cut; SHOTS
// are the source in/out points each scene shows; VO_STARTS is where each
// audio slice lands in reel time.
export const BEATS = {
  hook: 3.8,
  cafe: 3.15,
  stare: 1.5,
  source: 2.25,
  use: 3.43,
  outro: 3.37,
} as const;

export const SHOTS = {
  hook: { srcIn: 0, srcOut: 3.8 },
  cafe: { srcIn: 3.8, srcOut: 6.95 },
  stare: { srcIn: 6.95, srcOut: 8.45 },
  source: { srcIn: 9.5, srcOut: 11.75 },
  use: { srcIn: 11.75, srcOut: 15.18 },
} as const;

export const VO_STARTS: Record<string, number> = {
  "01-hello": 0,
  "02-source": 8.45,
};
