// Generated by scripts/gen-voiceover.mjs — do not edit by hand.
// Measured mp3 durations in seconds, before VO_RATE playback scaling.
// Regenerate: npm run voiceover -- scripts/voiceover/unicorn-cafe.json --durations-only
export const DURATIONS = {
  "01-hello": 8.453,
  "02-source": 5.964,
} as const;
