// Generated by scripts/gen-voiceover.mjs — do not edit by hand.
// Measured mp3 durations in seconds, before VO_RATE playback scaling.
// Regenerate: npm run voiceover -- scripts/voiceover/database-guide.json --durations-only
export const DURATIONS = {
  "01-hook": 3.762,
  "02-why": 4.783,
  "03-table": 5.666,
  "04-choice": 8.731,
  "05-cta": 4.69,
  "06-loop": 2.972,
} as const;
