// Generated by scripts/gen-voiceover.mjs — do not edit by hand.
// Measured mp3 durations in seconds, before VO_RATE playback scaling.
// Regenerate: npm run voiceover -- scripts/voiceover/btc-squeeze.json --durations-only
export const DURATIONS = {
  "01-hook": 6.641,
  "02-trigger": 12.957,
  "03-printer": 9.985,
  "04-clarity": 11.378,
  "05-shorts": 13.607,
  "06-squeeze": 5.851,
  "07-etf": 5.898,
  "08-formula": 8.034,
  "09-cta": 10.542,
} as const;
