// Generated by scripts/gen-voiceover.mjs — do not edit by hand.
// Measured mp3 durations in seconds, before VO_RATE playback scaling.
// Regenerate: npm run voiceover -- scripts/voiceover/yoloco-mcp.json --durations-only
export const DURATIONS = {
  "01-hook": 5.387,
  "02-agents": 4.969,
  "03-mcp": 4.969,
  "04-tools": 7.57,
  "05-ask": 6.409,
  "06-analyze": 4.737,
  "07-plan": 5.201,
  "08-cta": 4.04,
} as const;
