// Generated by scripts/gen-voiceover.mjs — do not edit by hand.
// Measured mp3 durations in seconds, before VO_RATE playback scaling.
// Regenerate: npm run voiceover -- scripts/voiceover/brands-paying-more.json --durations-only
export const DURATIONS = {
  "01-hook": 5.619,
  "02-money": 7.802,
  "03-trust": 4.876,
  "04-backlash": 4.458,
  "05-economics": 3.019,
  "06-fit": 7.059,
  "07-shift": 6.316,
  "08-measure": 4.226,
  "09-yoloco": 5.294,
} as const;
