// Generated by scripts/gen-voiceover.mjs — do not edit by hand.
// Measured mp3 durations in seconds, before VO_RATE playback scaling.
// Regenerate: npm run voiceover -- scripts/voiceover/gasoline-inflation.json --durations-only
export const DURATIONS = {
  "01-hook": 4.04,
  "02-shortage": 5.759,
  "03-proof": 6.455,
  "04-first-hit": 5.341,
  "05-field": 5.526,
  "06-chain": 6.594,
  "07-costs": 6.873,
  "08-hidden": 5.155,
  "09-definition": 7.198,
  "10-outro": 5.108,
} as const;
