// Generated by scripts/gen-voiceover.mjs — do not edit by hand.
// Measured mp3 durations in seconds, before VO_RATE playback scaling.
// Regenerate: npm run voiceover -- scripts/voiceover/khaby-silence.json --durations-only
export const DURATIONS = {
  "01-hook": 4.458,
  "02-job": 7.43,
  "03-nobody": 2.972,
  "04-chaos": 6.223,
  "05-opposite": 2.879,
  "06-silence": 5.713,
  "07-barrier": 4.04,
  "08-growth": 3.529,
  "09-lesson": 8.22,
  "10-yoloco": 4.644,
} as const;
