// Generated by scripts/gen-voiceover.mjs — do not edit by hand.
// Measured mp3 durations in seconds, before VO_RATE playback scaling.
// Regenerate: npm run voiceover -- scripts/voiceover/dollar-wait.json --durations-only
export const DURATIONS = {
  "01-hook": 4.969,
  "02-answer": 7.988,
  "03-fever": 7.012,
  "04-levels": 12.26,
  "05-why": 9.009,
  "06-counter": 9.845,
  "07-mistake": 7.384,
  "08-swap": 4.783,
  "09-who": 10.542,
  "10-plan": 13.932,
  "11-scenarios": 10.728,
  "12-cta": 9.288,
} as const;
