// Generated by scripts/gen-heygen.mjs — do not edit by hand.
// Presenter shots: where each talking-head insert lands in the reel and
// how long the generated file actually is (measured, at 1.0x — play it at
// VO_RATE like the voiceover track, and keep it muted: the audio already
// comes from public/voiceover/dollar-wait/.
// enabled:false shots are still cut (the concat offsets depend on them)
// but are not rendered — see "_disabled" in the manifest for why.
// Regenerate: npm run heygen -- scripts/presenter/dollar-wait.json
export const PRESENTER = {
  "p1-crowd": { clip: "02-answer", style: "hero", reelIn: 11.15, duration: 2, file: "p1-crowd.mp4", enabled: true },
  "p2-anxiety": { clip: "07-mistake", style: "hero", reelIn: 54.4333, duration: 2.72, file: "p2-anxiety.mp4", enabled: true },
  "p3-cta": { clip: "12-cta", style: "cta", reelIn: 100.127, duration: 3.56, file: "p3-cta.mp4", enabled: true },
} as const;
