// Generated by scripts/gen-voiceover.mjs — do not edit by hand.
// Measured mp3 durations in seconds, before VO_RATE playback scaling.
// Regenerate: npm run voiceover -- scripts/voiceover/phone-check.json --durations-only
export const DURATIONS = {
  "01-hook": 3.808,
  "02-date": 11.146,
  "03-loop": 5.805,
  "04-scope": 10.774,
  "05-fear": 7.198,
  "06-consent": 7.988,
  "07-inside": 9.474,
  "08-twist": 11.331,
  "09-condition": 6.78,
  "10-cta": 5.016,
} as const;
