// Generated by scripts/gen-voiceover.mjs — do not edit by hand.
// Measured mp3 durations in seconds, before VO_RATE playback scaling.
// Regenerate: npm run voiceover -- scripts/voiceover/youtube-netflix.json --durations-only
export const DURATIONS = {
  "01-hook": 4.319,
  "02-offer": 5.248,
  "03-netflix": 3.483,
  "04-television": 6.455,
  "05-problem": 5.991,
  "06-money": 7.059,
  "07-crazy": 2.322,
  "08-shift": 4.69,
  "09-followers": 6.734,
  "10-economy": 5.341,
  "11-yoloco": 2.694,
} as const;
