// HeyGen presenter shots for a reel.
//   node scripts/gen-heygen.mjs scripts/presenter/<manifest>.json [env-path]
//                               [--dry-run] [--only <shot-id>] [--keep-audio]
//
// The one rule this script exists to enforce: **the avatar never speaks its own
// voice.** Every shot is generated by uploading a slice of the ElevenLabs house
// clips that are already in public/voiceover/<id>/ and letting HeyGen lip-sync
// to that audio. So:
//   - the reel's audio track never changes, and durations.ts stays valid;
//   - the timeline does not move by a single frame;
//   - there is no second voice and no double-voice to duck.
// Using HeyGen's own TTS instead would re-voice the reel and invalidate every
// caption timing in timeline.ts, which is computed from the measured mp3s.
//
// Only the seconds actually used on screen are uploaded (`from`/`to` per shot),
// because HeyGen bills generated video length — a hero cut that shows the last
// six seconds of a clip must not pay for the first two.
//
// Output is WebM with an alpha channel: `output_format: "webm"` is what removes
// the background, and it is mutually exclusive with a `background` object. The
// avatar must have been trained with matting (the default for recent Digital
// Twins / Studio Avatars) or the API rejects the request.
//
// API shape per https://developers.heygen.com (v3):
//   POST https://api.heygen.com/v3/assets        multipart, returns asset id
//   POST https://api.heygen.com/v3/videos        returns { data: { video_id } }
//   GET  https://api.heygen.com/v3/videos/{id}   poll until status "completed"
import { mkdir, readFile, writeFile, unlink } from "node:fs/promises";
import { execFile } from "node:child_process";
import path from "node:path";
import { promisify } from "node:util";
import { fileURLToPath } from "node:url";

const run = promisify(execFile);
const API = "https://api.heygen.com";

// npm workspaces run the script with cwd = packages/video, but paths get typed
// from the repo root (`out/heygen/...`). Try both before giving up, so the
// command works from wherever it is natural to type it.
const resolveInput = async (p, repoRoot) => {
  for (const candidate of [path.resolve(p), path.resolve(repoRoot, p)]) {
    // eslint-disable-next-line no-await-in-loop
    if (await readFile(candidate).then(() => true, () => false)) return candidate;
  }
  throw new Error(`File not found: ${p} (looked in ${process.cwd()} and ${repoRoot})`);
};
const POLL_MS = 10_000;
const POLL_LIMIT = 180; // 30 minutes — a 10s shot renders in ~1-3 min

const root = path.resolve(path.dirname(fileURLToPath(import.meta.url)), "..");

/* ------------------------------------------------------------------ args */

// `--only <id>` takes a value, so its value must not fall through into the
// positional list — otherwise it gets read as the optional env-path argument.
const VALUE_FLAGS = new Set(["--only", "--slice", "--slice-concat"]);

const argv = process.argv.slice(2);
const flags = new Set();
const values = new Map();
const positional = [];
for (let i = 0; i < argv.length; i += 1) {
  const arg = argv[i];
  if (VALUE_FLAGS.has(arg)) {
    const value = argv[i + 1];
    if (!value || value.startsWith("--")) throw new Error(`${arg} needs a value`);
    values.set(arg, value);
    i += 1;
  } else if (arg.startsWith("--")) {
    flags.add(arg);
  } else {
    positional.push(arg);
  }
}

const only = values.get("--only") ?? null;
const sliceFrom = values.get("--slice") ?? null;
const sliceConcatFrom = values.get("--slice-concat") ?? null;
const buildMaster = flags.has("--master");
const manifestPath = positional[0];
const envPath = positional[1] ?? path.resolve(root, "../../.env");
const dryRun = flags.has("--dry-run");
const keepAudio = flags.has("--keep-audio");

if (!manifestPath) {
  throw new Error(
    "Usage: node gen-heygen.mjs <manifest.json> [env-path] [--dry-run] [--only <shot-id>]",
  );
}

/* -------------------------------------------------------------------- env */

const fromEnvFile = async (key) => {
  const text = await readFile(envPath, "utf8").catch(() => "");
  return text
    .split(/\r?\n/)
    .find((line) => line.startsWith(`${key}=`))
    ?.slice(key.length + 1)
    .trim()
    .replace(/^['"]|['"]$/g, "");
};

const env = async (key) => process.env[key] ?? (await fromEnvFile(key));

// The manifest names the character — "${HEYGEN_AVATAR_VIEW_ID}" or a bare id —
// because an account holds several usable ones (a Digital Twin and five
// near-identical «Podcaster in …» photo looks) and which one a reel uses is
// part of the reel. There is deliberately NO fallback: HEYGEN_AVATAR_ID used
// to be one, and it held the avatar GROUP id, which HeyGen answers with
// "Avatar not found" — a session that hit that went shopping in the group
// list and picked whichever podcaster came first.
const resolveAvatarId = async (manifest) => {
  const raw = manifest.avatarId;
  if (!raw) throw new Error(`The manifest has no "avatarId". Ask the author which face — never pick one from the avatar list.`);
  const named = typeof raw === "string" ? raw.match(/^\$\{(\w+)\}$/) : null;
  if (!named) return raw;
  const value = await env(named[1]);
  if (!value) {
    throw new Error(`${raw} is not set in the environment or ${envPath}. Set it — do not substitute another avatar.`);
  }
  return value;
};

// Before a cent is spent the face is named back from HeyGen, and checked
// against the manifest's "avatarName" when it has one. A wrong id then fails
// on the free dry run instead of after the paid render.
const confirmFace = async (manifest) => {
  const avatarId = await resolveAvatarId(manifest);
  const apiKey = await env("HEYGEN_API_KEY");
  if (!apiKey) throw new Error(`HEYGEN_API_KEY not found in env or ${envPath}`);
  let info;
  try {
    info = await heygen(apiKey, "GET", `/v2/avatar/${avatarId}/details`);
  } catch (error) {
    if (/not found/i.test(String(error.message))) {
      throw new Error(`HeyGen has no avatar ${avatarId} (from ${manifest.avatarId}) — is that a group id?`);
    }
    process.stdout.write(`! could not look the avatar up (${String(error.message).slice(0, 120)}) — check the face by hand\n`);
    return avatarId;
  }
  const name = info?.name ?? "?";
  process.stdout.write(`FACE: ${name} (${info?.type ?? "?"}, ${avatarId})\n`);
  if (info?.preview_image_url) process.stdout.write(`      preview: ${info.preview_image_url}\n`);
  if (manifest.avatarName && manifest.avatarName !== name) {
    throw new Error(`Wrong face: the manifest expects «${manifest.avatarName}», ${avatarId} is «${name}».`);
  }
  return avatarId;
};

// Per-second USD, per https://developers.heygen.com/docs/pricing — billed from
// the prepaid wallet. A photo avatar (an AI look) and a Digital Twin are NOT
// the same price on the same engine, and the two tables cross: a photo avatar
// costs more than a twin on Avatar III and less on Avatar IV. Getting this
// wrong prints a estimate that is off by 3x, which is worse than not printing
// one, so the manifest has to say which kind of character it is using.
const RATE = {
  digital_twin: { avatar_iii: 0.0167, avatar_iv: 0.0667, avatar_v: 0.0667 },
  photo: { avatar_iii: 0.0433, avatar_iv: 0.05 },
};

/* ------------------------------------------------------------------ audio */

const probeDuration = async (file) => {
  const { stdout } = await run("ffprobe", ["-v", "error",
    "-show_entries", "format=duration", "-of", "csv=p=0", file]);
  return Math.round(parseFloat(stdout.trim()) * 1000) / 1000;
};

// Copy the used slice out of the house clip. Re-encoded rather than stream-copied
// so the cut is sample-accurate: an mp3 stream copy snaps to the frame grid and
// would drift the lip-sync against the reel by up to 26ms.
const sliceAudio = async (source, target, from, to) => {
  await run("ffmpeg", ["-v", "error", "-y",
    "-i", source,
    "-ss", String(from), "-to", String(to),
    "-c:a", "libmp3lame", "-q:a", "2",
    target]);
  return probeDuration(target);
};

/* -------------------------------------------------------------------- api */

const heygen = async (apiKey, method, route, { json, form } = {}) => {
  const response = await fetch(`${API}${route}`, {
    method,
    headers: {
      "X-Api-Key": apiKey,
      // multipart sets its own Content-Type (with the boundary) — never override
      ...(json ? { "Content-Type": "application/json" } : {}),
    },
    body: json ? JSON.stringify(json) : form,
  });
  const text = await response.text();
  let body;
  try {
    body = JSON.parse(text);
  } catch {
    body = { raw: text };
  }
  if (!response.ok) {
    throw new Error(`HeyGen ${method} ${route} → ${response.status}: ${text.slice(0, 600)}`);
  }
  // v3 wraps payloads in { data: ... }; some routes answer flat. Tolerate both.
  return body.data ?? body;
};

const uploadAudio = async (apiKey, file) => {
  const buffer = await readFile(file);
  const form = new FormData();
  form.append("file", new Blob([buffer], { type: "audio/mpeg" }), path.basename(file));
  const asset = await heygen(apiKey, "POST", "/v3/assets", { form });
  const id = asset.id ?? asset.asset_id ?? asset.asset?.id;
  if (!id) throw new Error(`No asset id in upload response: ${JSON.stringify(asset).slice(0, 400)}`);
  return id;
};

const waitForVideo = async (apiKey, videoId, label) => {
  for (let i = 0; i < POLL_LIMIT; i += 1) {
    const status = await heygen(apiKey, "GET", `/v3/videos/${videoId}`);
    if (status.status === "completed") {
      const url = status.video_url ?? status.url;
      if (!url) throw new Error(`${label}: completed but no video_url`);
      return url;
    }
    if (status.status === "failed") {
      throw new Error(`${label}: HeyGen reported failed — ${JSON.stringify(status.error ?? status).slice(0, 400)}`);
    }
    process.stdout.write(`  ${label}: ${status.status ?? "pending"} …\n`);
    await new Promise((resolve) => setTimeout(resolve, POLL_MS));
  }
  throw new Error(`${label}: still not finished after ${(POLL_LIMIT * POLL_MS) / 60000} minutes`);
};

const download = async (url, target) => {
  const response = await fetch(url);
  if (!response.ok) throw new Error(`Download failed: ${response.status} ${url}`);
  await writeFile(target, Buffer.from(await response.arrayBuffer()));
};

/* ------------------------------------------------------------- generated */

// Same discipline as durations.ts: the Remotion side must never hand-type a
// measured number. This module is what the presenter cut reads.
const writePresenterModule = async (modulePath, id, shots) => {
  const body = shots
    .map((s) =>
      `  "${s.id}": { clip: "${s.clip}", style: "${s.style}", ` +
      `reelIn: ${s.reelIn}, duration: ${s.duration}, file: "${s.file}", ` +
      `enabled: ${s.enabled !== false} },`,
    )
    .join("\n");
  await mkdir(path.dirname(modulePath), { recursive: true });
  await writeFile(
    modulePath,
    `// Generated by scripts/gen-heygen.mjs — do not edit by hand.\n` +
      `// Presenter shots: where each talking-head insert lands in the reel and\n` +
      `// how long the generated file actually is (measured, at 1.0x — play it at\n` +
      `// VO_RATE like the voiceover track, and keep it muted: the audio already\n` +
      `// comes from public/voiceover/${id}/.\n` +
      `// enabled:false shots are still cut (the concat offsets depend on them)\n` +
      `// but are not rendered — see "_disabled" in the manifest for why.\n` +
      `// Regenerate: npm run heygen -- scripts/presenter/${id}.json\n` +
      `export const PRESENTER = {\n${body}\n} as const;\n`,
  );
};

/* ----------------------------------------------------------- master mode */

// One avatar generation for the WHOLE reel instead of six short ones: the
// twelve house clips are laid end to end into a single master mp3, that gets
// generated once (in the HeyGen UI or through the API), and the returned video
// is cut into shots afterwards. More seconds billed, but one upload instead of
// six — and the insert points can then be moved without regenerating anything.
//
// Offsets are the running sum of the MEASURED clip durations, so a shot's
// position in the master is `offset[clip] + shot.from`. Placement is done with
// adelay+amix rather than the concat demuxer: mp3 encoder delay makes a concat
// drift a few milliseconds per join, and twelve joins of drift would be
// audible against the reel's own track.
const clipOrder = async (manifest) => {
  const voManifestPath = path.resolve(
    root,
    manifest.voiceoverManifest ?? `scripts/voiceover/${manifest.templateId}.json`,
  );
  const vo = JSON.parse(await readFile(voManifestPath, "utf8"));
  return vo.lines.map(([name]) => name);
};

const buildMasterAudio = async (manifest) => {
  const names = await clipOrder(manifest);
  const voiceoverDir = path.resolve(root, manifest.voiceoverDir);
  const files = names.map((n) => path.join(voiceoverDir, `${n}.mp3`));

  const offsets = {};
  let cursor = 0;
  for (const [i, name] of names.entries()) {
    offsets[name] = Math.round(cursor * 1000) / 1000;
    cursor += await probeDuration(files[i]);
  }
  const total = Math.round(cursor * 1000) / 1000;

  const outFile = path.resolve(root, "../../out/presenter-slices", `${manifest.templateId}-master.mp3`);
  await mkdir(path.dirname(outFile), { recursive: true });

  const inputs = files.flatMap((f) => ["-i", f]);
  const chains = names.map(
    (name, i) =>
      `[${i}:a]aformat=channel_layouts=mono:sample_rates=44100,` +
      `adelay=delays=${Math.round(offsets[name] * 1000)}:all=1[a${i}]`,
  );
  const mix = `${names.map((_, i) => `[a${i}]`).join("")}amix=inputs=${names.length}:normalize=0:dropout_transition=0[out]`;

  await run("ffmpeg", ["-v", "error", "-y", ...inputs,
    "-filter_complex", `${chains.join(";")};${mix}`,
    "-map", "[out]", "-c:a", "libmp3lame", "-q:a", "2", outFile],
    { maxBuffer: 16 * 1024 * 1024 });

  const measured = await probeDuration(outFile);
  const mapFile = `${outFile.replace(/\.mp3$/, "")}.json`;
  await writeFile(mapFile, `${JSON.stringify({ total, measured, offsets }, null, 2)}\n`);
  return { outFile, mapFile, offsets, total, measured, names };
};

/* ------------------------------------------------------------ slice mode */

// Cut the finished master video into the manifest's shots. Every cut is
// re-encoded from an exact in-point rather than stream-copied to the nearest
// keyframe, which on a 30fps h264/vp9 export could be up to a second away.
const sliceMaster = async (manifest, masterVideo) => {
  const mapFile = path.resolve(
    root, "../../out/presenter-slices", `${manifest.templateId}-master.json`,
  );
  const map = JSON.parse(await readFile(mapFile, "utf8").catch(() => {
    throw new Error(`No ${path.relative(root, mapFile)} — run with --master first.`);
  }));

  const videoLen = await probeDuration(masterVideo);
  const drift = videoLen - map.total;
  process.stdout.write(
    `master audio ${map.total}s → master video ${videoLen}s (drift ${drift >= 0 ? "+" : ""}${drift.toFixed(3)}s)\n`,
  );
  if (Math.abs(drift) > 0.25) {
    process.stdout.write(
      `  WARNING: the generated video is not the length of the audio it was made from.\n` +
        `  Every shot after the first will sit wrong. Re-export without added intro/outro,\n` +
        `  or trim the master to ${map.total}s before slicing.\n`,
    );
  }

  const outDir = path.resolve(root, manifest.outDir);
  await mkdir(outDir, { recursive: true });
  const ext = path.extname(masterVideo) || ".mp4";
  const shots = only ? manifest.shots.filter((s) => s.id === only) : manifest.shots;
  const done = [];

  for (const shot of shots) {
    const offset = map.offsets[shot.clip];
    if (offset === undefined) throw new Error(`${shot.id}: clip "${shot.clip}" is not in the master`);
    const inPoint = offset + shot.from;
    const length = shot.to - shot.from;
    const file = `${shot.id}${ext}`;
    const target = path.join(outDir, file);

    // -ss before -i seeks fast; -accurate_seek plus a re-encode keeps it frame-exact.
    await run("ffmpeg", ["-v", "error", "-y",
      "-accurate_seek", "-ss", String(inPoint), "-t", String(length),
      "-i", masterVideo,
      // keep alpha if the master has it: vp9 with yuva420p, else plain h264
      ...(ext === ".webm"
        ? ["-c:v", "libvpx-vp9", "-pix_fmt", "yuva420p", "-b:v", "0", "-crf", "28", "-row-mt", "1"]
        : ["-c:v", "libx264", "-crf", "18", "-pix_fmt", "yuv420p"]),
      "-an", target],
      { maxBuffer: 16 * 1024 * 1024 });

    const duration = await probeDuration(target);
    process.stdout.write(
      `${shot.id}  ${shot.style.padEnd(6)}  master ${inPoint.toFixed(3)}s +${length.toFixed(3)}s ` +
        `→ ${path.relative(root, target)} (${duration}s)\n`,
    );
    done.push({ ...shot, duration, file });
  }

  const modulePath = path.resolve(
    root,
    manifest.presenterModule ?? `src/templates/${manifest.templateId}/presenter.ts`,
  );
  await writePresenterModule(modulePath, manifest.templateId, done);
  process.stdout.write(`\n${done.length} shot(s) → ${path.relative(root, modulePath)}\n`);
};

/* ------------------------------------------ generate: shots as one upload */

// Build ONE mp3 of just the shots, laid end to end in manifest order, and
// generate a single avatar video from it. Billing is per second of output, so
// this costs exactly the sum of the shot lengths — but as one call, because the
// docs never state whether a video has a minimum billed duration, and three
// 2-3s calls could quietly cost more than one 8s call. It also keeps the
// avatar's framing and background identical across every insert, which is what
// went wrong the last time the shots were assembled by hand.
const buildShotsAudio = async (manifest) => {
  const voiceoverDir = path.resolve(root, manifest.voiceoverDir);
  const outDir = path.resolve(root, "../../out/presenter-slices");
  await mkdir(outDir, { recursive: true });

  const parts = [];
  let cursor = 0;
  for (const shot of manifest.shots) {
    const slice = path.join(outDir, `${shot.id}.slice.mp3`);
    const len = await sliceAudio(
      path.join(voiceoverDir, `${shot.clip}.mp3`), slice, shot.from, shot.to,
    );
    parts.push({ id: shot.id, file: slice, at: cursor, len });
    cursor += shot.to - shot.from;
  }

  const outFile = path.join(outDir, `${manifest.templateId}-shots.mp3`);
  const inputs = parts.flatMap((p) => ["-i", p.file]);
  const chains = parts.map(
    (p, i) =>
      `[${i}:a]aformat=channel_layouts=mono:sample_rates=44100,` +
      `adelay=delays=${Math.round(p.at * 1000)}:all=1[a${i}]`,
  );
  const mix = `${parts.map((_, i) => `[a${i}]`).join("")}amix=inputs=${parts.length}:normalize=0:dropout_transition=0[out]`;
  await run("ffmpeg", ["-v", "error", "-y", ...inputs,
    "-filter_complex", `${chains.join(";")};${mix}`,
    "-map", "[out]", "-c:a", "libmp3lame", "-q:a", "2", outFile],
    { maxBuffer: 16 * 1024 * 1024 });

  if (!keepAudio) {
    for (const p of parts) await unlink(p.file).catch(() => {});
  }
  return { outFile, total: cursor, measured: await probeDuration(outFile), parts };
};

/* ----------------------------------------------- slice: shots back-to-back */

// The layout you get when the six per-shot slices are concatenated into ONE
// upload (the only way to do a single generation and still stay under HeyGen's
// per-video length cap). Shot n starts at the running sum of the previous
// shots' lengths.
//
// The returned video is never exactly the length of the audio that made it —
// encoders trim and pad — so offsets are scaled by the measured ratio instead
// of trusted raw. Without that the last shot can land a tenth of a second late,
// which at 30fps is three frames of visible lip-sync error.
const sliceConcat = async (manifest, video) => {
  const videoLen = await probeDuration(video);
  const nominal = manifest.shots.reduce((t, s) => t + (s.to - s.from), 0);
  const scale = videoLen / nominal;
  process.stdout.write(
    `shots ${nominal.toFixed(3)}s → video ${videoLen}s ` +
      `(scale ${scale.toFixed(5)}, drift ${((videoLen - nominal) * 1000).toFixed(0)}ms)\n`,
  );
  if (Math.abs(videoLen - nominal) > 1) {
    throw new Error(
      `The video is ${videoLen}s but the shots add up to ${nominal.toFixed(3)}s. ` +
        `That is not the six slices concatenated — check what was uploaded.`,
    );
  }

  const outDir = path.resolve(root, manifest.outDir);
  await mkdir(outDir, { recursive: true });
  const ext = path.extname(video) || ".mp4";
  const wanted = only ? manifest.shots.filter((s) => s.id === only) : manifest.shots;
  const done = [];

  let cursor = 0;
  for (const shot of manifest.shots) {
    const length = shot.to - shot.from;
    if (wanted.includes(shot)) {
      const inPoint = Math.round(cursor * scale * 1000) / 1000;
      const outLen = Math.round(length * scale * 1000) / 1000;
      const file = `${shot.id}${ext}`;
      const target = path.join(outDir, file);
      await run("ffmpeg", ["-v", "error", "-y",
        "-accurate_seek", "-ss", String(inPoint), "-t", String(outLen),
        "-i", video,
        ...(ext === ".webm"
          ? ["-c:v", "libvpx-vp9", "-pix_fmt", "yuva420p", "-b:v", "0", "-crf", "28", "-row-mt", "1"]
          : ["-c:v", "libx264", "-crf", "18", "-pix_fmt", "yuv420p"]),
        "-an", target],
        { maxBuffer: 16 * 1024 * 1024 });
      const duration = await probeDuration(target);
      process.stdout.write(
        `${shot.id.padEnd(14)} ${shot.style.padEnd(6)} ` +
          `src ${inPoint.toFixed(3)}s +${outLen.toFixed(3)}s → ` +
          `${path.relative(root, target)} (${duration}s)\n`,
      );
      done.push({ ...shot, duration, file });
    }
    cursor += length;
  }

  const modulePath = path.resolve(
    root,
    manifest.presenterModule ?? `src/templates/${manifest.templateId}/presenter.ts`,
  );
  await writePresenterModule(modulePath, manifest.templateId, done);
  process.stdout.write(`\n${done.length} shot(s) → ${path.relative(root, modulePath)}\n`);
};

/* -------------------------------------------------------------------- run */

const manifest = JSON.parse(await readFile(path.resolve(manifestPath), "utf8"));

if (sliceConcatFrom) {
  await sliceConcat(manifest, await resolveInput(sliceConcatFrom, path.resolve(root, "../..")));
  process.exit(0);
}

// End to end: shots → one mp3 → one generation → download → slice.
if (flags.has("--generate")) {
  const engine = manifest.engine ?? "avatar_iv";
  const kind = manifest.avatarKind ?? "digital_twin";
  const rate = RATE[kind]?.[engine];
  if (rate === undefined) {
    throw new Error(`No published price for ${kind} on ${engine} — check the manifest.`);
  }
  const avatarId = await confirmFace(manifest);
  const audio = await buildShotsAudio(manifest);
  const cost = audio.total * rate;
  process.stdout.write(
    `${manifest.shots.length} shot(s), ${audio.total.toFixed(3)}s ` +
      `(mp3 measured ${audio.measured}s)\n` +
      `${kind} on ${engine} @ $${rate}/s → estimated $${cost.toFixed(3)}\n`,
  );
  for (const p of audio.parts) {
    process.stdout.write(`  ${p.id.padEnd(12)} at ${p.at.toFixed(3)}s  +${p.len}s\n`);
  }

  if (dryRun) {
    process.stdout.write(`\nDry run — nothing uploaded, no credits spent.\n`);
    process.exit(0);
  }

  const apiKey = await env("HEYGEN_API_KEY");
  if (!apiKey) throw new Error(`HEYGEN_API_KEY not found in env or ${envPath}`);

  process.stdout.write(`\nuploading ${path.basename(audio.outFile)} …\n`);
  const audioAssetId = await uploadAudio(apiKey, audio.outFile);
  const body = {
    type: "avatar",
    avatar_id: avatarId,
    audio_asset_id: audioAssetId,
    aspect_ratio: manifest.concatAspect ?? "1:1",
    resolution: manifest.resolution ?? "1080p",
    output_format: manifest.outputFormat ?? "mp4",
    engine: { type: engine },
    title: `${manifest.templateId} presenter shots`,
  };
  const created = await heygen(apiKey, "POST", "/v3/videos", { json: body });
  const videoId = created.video_id ?? created.id;
  if (!videoId) throw new Error(`No video_id in ${JSON.stringify(created).slice(0, 400)}`);
  process.stdout.write(`video_id ${videoId}\n`);

  const url = await waitForVideo(apiKey, videoId, manifest.templateId);
  const ext = (manifest.outputFormat ?? "mp4") === "webm" ? ".webm" : ".mp4";
  const raw = path.resolve(root, "../../out/heygen", `${manifest.templateId}-shots${ext}`);
  await mkdir(path.dirname(raw), { recursive: true });
  await download(url, raw);
  process.stdout.write(`downloaded → ${path.relative(path.resolve(root, "../.."), raw)}\n\n`);

  await sliceConcat(manifest, raw);
  process.exit(0);
}

if (buildMaster) {
  const m = await buildMasterAudio(manifest);
  process.stdout.write(
    `\nMaster audio for ${manifest.templateId}: ${m.names.length} clips, ${m.measured}s\n` +
      `  ${path.relative(path.resolve(root, "../.."), m.outFile)}\n` +
      `  ${path.relative(path.resolve(root, "../.."), m.mapFile)}  (clip offsets)\n\n` +
      `Upload that mp3 to HeyGen as the avatar's voice (Upload audio — never TTS),\n` +
      `export 9:16 1080p WebM/transparent, then cut it up with:\n` +
      `  npm run heygen -- ${manifestPath} --slice <master-video>\n`,
  );
  process.exit(0);
}

if (sliceFrom) {
  await sliceMaster(manifest, await resolveInput(sliceFrom, path.resolve(root, "../..")));
  process.exit(0);
}

// Shots generated by hand in the HeyGen UI and dropped into outDir as
// <shot-id>.webm / .mp4. Nothing to generate — just measure what is there,
// check each file against the length of the audio it was made from, and write
// the module the composite reads.
if (flags.has("--adopt")) {
  const outDir = path.resolve(root, manifest.outDir);
  const found = [];
  const missing = [];
  for (const shot of manifest.shots) {
    let file = null;
    for (const ext of [".webm", ".mov", ".mp4"]) {
      const candidate = path.join(outDir, `${shot.id}${ext}`);
      // eslint-disable-next-line no-await-in-loop
      if (await readFile(candidate).then(() => true, () => false)) {
        file = `${shot.id}${ext}`;
        break;
      }
    }
    if (!file) {
      missing.push(shot.id);
      continue;
    }
    const duration = await probeDuration(path.join(outDir, file));
    const expected = Math.round((shot.to - shot.from) * 1000) / 1000;
    const off = duration - expected;
    process.stdout.write(
      `${shot.id.padEnd(14)} ${file.padEnd(20)} ${duration}s ` +
        `(audio ${expected}s, ${off >= 0 ? "+" : ""}${off.toFixed(3)}s)` +
        `${Math.abs(off) > 0.15 ? "  ← WARNING: lip-sync will drift" : ""}\n`,
    );
    found.push({ ...shot, duration, file });
  }
  if (missing.length) {
    process.stdout.write(
      `\nNot found in ${path.relative(root, outDir)}: ${missing.join(", ")}\n` +
        `Name each export after its shot id, e.g. p1-answer.webm\n`,
    );
  }
  if (found.length === 0) throw new Error("No presenter shots found — nothing to write.");
  const modulePath = path.resolve(
    root,
    manifest.presenterModule ?? `src/templates/${manifest.templateId}/presenter.ts`,
  );
  await writePresenterModule(modulePath, manifest.templateId, found);
  process.stdout.write(`\n${found.length} shot(s) → ${path.relative(root, modulePath)}\n`);
  process.exit(0);
}

const shots = only ? manifest.shots.filter((s) => s.id === only) : manifest.shots;
if (shots.length === 0) throw new Error(`No shot matching --only ${only}`);

const voiceoverDir = path.resolve(root, manifest.voiceoverDir);
const outDir = path.resolve(root, manifest.outDir);
await mkdir(outDir, { recursive: true });

// "hero" fills the frame (the face IS the shot); "corner" is the round PiP over
// running graphics, so it wants a square canvas with the head centred.
const ASPECT = { hero: "9:16", corner: "1:1" };

const avatarId = await confirmFace(manifest);
const billed = shots.reduce((total, s) => total + (s.to - s.from), 0);
process.stdout.write(
  `${shots.length} shot(s), ${billed.toFixed(1)}s of avatar video to generate ` +
    `(${manifest.resolution ?? "1080p"}, ${manifest.outputFormat ?? "webm"})\n`,
);

if (dryRun) {
  for (const shot of shots) {
    const aspect = ASPECT[shot.style];
    if (!aspect) throw new Error(`${shot.id}: unknown style "${shot.style}"`);
    const source = path.join(voiceoverDir, `${shot.clip}.mp3`);
    const sourceLen = await probeDuration(source);
    if (shot.to > sourceLen + 0.01) {
      throw new Error(`${shot.id}: to=${shot.to}s is past the end of ${shot.clip}.mp3 (${sourceLen}s)`);
    }
    process.stdout.write(
      `\n${shot.id}  ${shot.style}  ${aspect}  ` +
        `${shot.clip}[${shot.from}–${shot.to}] = ${(shot.to - shot.from).toFixed(2)}s  ` +
        `→ reel ${shot.reelIn}s\n` +
        `${JSON.stringify(
          {
            type: "avatar",
            avatar_id: manifest.avatarId,
            audio_asset_id: "<from POST /v3/assets>",
            aspect_ratio: aspect,
            resolution: manifest.resolution ?? "1080p",
            output_format: manifest.outputFormat ?? "webm",
            engine: { type: manifest.engine ?? "avatar_iv" },
            title: `${manifest.templateId} ${shot.id}`,
          },
          null,
          2,
        )}\n`,
    );
  }
  process.stdout.write(`\nDry run — nothing uploaded, no credits spent.\n`);
  process.exit(0);
}

const apiKey = await env("HEYGEN_API_KEY");
if (!apiKey) throw new Error(`HEYGEN_API_KEY not found in env or ${envPath}`);


const done = [];
for (const shot of shots) {
  const aspect = ASPECT[shot.style];
  if (!aspect) throw new Error(`${shot.id}: unknown style "${shot.style}"`);

  const source = path.join(voiceoverDir, `${shot.clip}.mp3`);
  const slice = path.join(outDir, `${shot.id}.slice.mp3`);
  const sliceLen = await sliceAudio(source, slice, shot.from, shot.to);
  process.stdout.write(`${shot.id}: ${sliceLen}s of ${shot.clip}.mp3 → uploading\n`);

  const audioAssetId = await uploadAudio(apiKey, slice);
  const created = await heygen(apiKey, "POST", "/v3/videos", {
    json: {
      type: "avatar",
      avatar_id: avatarId,
      audio_asset_id: audioAssetId,
      aspect_ratio: aspect,
      resolution: manifest.resolution ?? "1080p",
      output_format: manifest.outputFormat ?? "webm",
      engine: { type: manifest.engine ?? "avatar_iv" },
      title: `${manifest.templateId} ${shot.id}`,
    },
  });

  const videoId = created.video_id ?? created.id;
  if (!videoId) throw new Error(`${shot.id}: no video_id in ${JSON.stringify(created).slice(0, 400)}`);
  process.stdout.write(`  ${shot.id}: video_id ${videoId}\n`);

  const url = await waitForVideo(apiKey, videoId, shot.id);
  const file = `${shot.id}.webm`;
  const target = path.join(outDir, file);
  await download(url, target);
  if (!keepAudio) await unlink(slice).catch(() => {});

  const duration = await probeDuration(target);
  process.stdout.write(`  ${shot.id}: ${path.relative(root, target)} (${duration}s)\n`);
  // A generated shot that is not the length of its audio means the lip-sync will
  // drift against the reel — catch it here, not in the render.
  if (Math.abs(duration - sliceLen) > 0.15) {
    process.stdout.write(
      `  WARNING ${shot.id}: video is ${duration}s but its audio slice is ${sliceLen}s — ` +
        `the lip-sync will drift. Re-generate or trim before compositing.\n`,
    );
  }
  done.push({ ...shot, duration, file });
}

const modulePath = path.resolve(
  root,
  manifest.presenterModule ?? `src/templates/${manifest.templateId}/presenter.ts`,
);
await writePresenterModule(modulePath, manifest.templateId, done);
process.stdout.write(`\n${done.length} shot(s) → ${path.relative(root, modulePath)}\n`);
