// QR matrix for a template, as a generated module the scene renders itself
// (so the modules can animate). A PNG would do for a static code; this keeps
// the code in the palette and lets it assemble on screen.
//   node scripts/gen-qr.mjs <templateId> <url> [ecLevel=M]
import { writeFile } from "node:fs/promises";
import path from "node:path";
import { fileURLToPath } from "node:url";
import QRCode from "qrcode";

const [templateId, text, level = "M", name = "qr"] = process.argv.slice(2);
if (!templateId || !text) {
  console.error("Usage: node scripts/gen-qr.mjs <templateId> <url> [L|M|Q|H] [moduleName=qr]");
  process.exit(1);
}
const root = path.resolve(path.dirname(fileURLToPath(import.meta.url)), "..");
const q = QRCode.create(text, { errorCorrectionLevel: level });
const n = q.modules.size;
const bits = Array.from(q.modules.data, (b) => (b ? "1" : "0")).join("");
const out = path.join(root, "src/templates", templateId, `${name}.ts`);
await writeFile(
  out,
  `// Generated by scripts/gen-qr.mjs — do not edit by hand.\n` +
    `// ${text} · EC level ${level} · ${n}×${n} modules, row-major, 1 = dark.\n` +
    `// Regenerate: node scripts/gen-qr.mjs ${templateId} ${text} ${level} ${name}\n` +
    `export const QR = { text: ${JSON.stringify(text)}, size: ${n}, bits: ${JSON.stringify(bits)} } as const;\n`,
);
console.log(`wrote ${path.relative(root, out)} (${n}×${n})`);
