// Normalise footage for a reel and generate the measured `footage.ts` beside
// `durations.ts`.
//
// The discipline is the voiceover pass's: the config names the shots and their
// in/out points, ffmpeg cuts them to one fps/size, and ffprobe MEASURES what
// came out. A scene reads the generated module — it never hard-codes a clip
// length, because a re-cut would silently desync every animation keyed to it.
//
// Usage: node scripts/gen-footage.mjs scripts/footage/<id>.json
import { execFileSync } from "node:child_process";
import { mkdirSync, readFileSync, writeFileSync } from "node:fs";
import { dirname, resolve } from "node:path";
import { fileURLToPath } from "node:url";

const here = dirname(fileURLToPath(import.meta.url));
const pkg = resolve(here, "..");

const configPath = process.argv[2];
if (!configPath) {
  console.error("usage: node scripts/gen-footage.mjs scripts/footage/<id>.json");
  process.exit(1);
}
const cfgFile = resolve(process.cwd(), configPath);
const cfg = JSON.parse(readFileSync(cfgFile, "utf8"));

const srcDir = resolve(dirname(cfgFile), cfg.sourceDir);
const outDir = resolve(pkg, "public/footage", cfg.id);
mkdirSync(outDir, { recursive: true });

const probe = (file) =>
  JSON.parse(
    execFileSync("ffprobe", [
      "-v", "error",
      "-select_streams", "v:0",
      "-show_entries", "stream=width,height,r_frame_rate:format=duration",
      "-of", "json",
      file,
    ]).toString(),
  );

const { crop, width, fps } = cfg;
const measured = [];

for (const shot of cfg.shots) {
  const src = resolve(srcDir, shot.file);
  const dst = resolve(outDir, `${shot.name}.mp4`);
  const dur = Number((shot.out - shot.in).toFixed(3));
  if (!(dur > 0)) throw new Error(`${shot.name}: out must be after in`);

  // -ss before -i seeks fast; the re-encode below makes the cut frame-exact
  // anyway, and the source is all-keyframe screen capture.
  execFileSync("ffmpeg", [
    "-v", "error", "-y",
    "-ss", String(shot.in),
    "-t", String(dur),
    "-i", src,
    "-an",
    "-vf", `crop=${crop.w}:${crop.h}:${crop.x}:${crop.y},scale=${width}:-2,fps=${fps}`,
    "-c:v", "libx264", "-preset", "slow", "-crf", "17",
    "-pix_fmt", "yuv420p",
    dst,
  ]);

  const p = probe(dst);
  const s = p.streams[0];
  const [num, den] = s.r_frame_rate.split("/").map(Number);
  measured.push({
    name: shot.name,
    seconds: Number(Number(p.format.duration).toFixed(3)),
    width: s.width,
    height: s.height,
    fps: Number((num / den).toFixed(3)),
    proves: shot.proves ?? "",
  });
  console.log(
    `Cut public/footage/${cfg.id}/${shot.name}.mp4 — ` +
      `${measured.at(-1).seconds}s @ ${s.width}x${s.height} ${measured.at(-1).fps}fps`,
  );
}

const bad = measured.filter((m) => m.fps !== fps);
if (bad.length) throw new Error(`fps mismatch: ${bad.map((b) => b.name).join(", ")}`);

const body = measured
  .map(
    (m) =>
      `  "${m.name}": { seconds: ${m.seconds}, width: ${m.width}, height: ${m.height} },` +
      (m.proves ? ` // ${m.proves}` : ""),
  )
  .join("\n");

const ts = `// Generated by scripts/gen-footage.mjs — do not edit by hand.
// Measured after the cut, not copied from the config: the config asks for a
// range, ffmpeg delivers whole frames, and the two differ by up to one frame.
// Regenerate: node scripts/gen-footage.mjs ${configPath}
export const FOOTAGE = {
${body}
} as const;

/** Every clip is cut to this rate; a scene may assume it. */
export const FOOTAGE_FPS = ${fps};

export type FootageShot = keyof typeof FOOTAGE;
`;

const tsPath = resolve(pkg, "src/templates", cfg.id, "footage.ts");
writeFileSync(tsPath, ts);
console.log(`Measured ${measured.length} shots → src/templates/${cfg.id}/footage.ts`);
