// Scaffolds a new voiceover reel: template skeleton wired to the reel engine,
// a voiceover manifest in the author's voice, a scenario file, and the registry
// entry. Everything mechanical about starting a reel happens here so the only
// work left is the scenario itself — palette, timeline, scenes.
//
//   node scripts/new-reel.mjs <id> --name "Title" \
//        --beats hook,problem,proof,fix,finale [--lines 6] [--force]
//
// Next steps it prints are the pipeline in
// .claude/skills/reel-production/SKILL.md.
import { mkdir, readFile, writeFile, access } from "node:fs/promises";
import path from "node:path";
import { fileURLToPath } from "node:url";

// Resolved from the env by gen-voiceover — see CLAUDE.md, «The voice».
const VOICE_REF = "${ELEVENLABS_VOICE_ID}";

const root = path.resolve(path.dirname(fileURLToPath(import.meta.url)), "..");
const repoRoot = path.resolve(root, "../..");

const argv = process.argv.slice(2);
const flags = new Map();
const positional = [];
for (let i = 0; i < argv.length; i += 1) {
  if (argv[i].startsWith("--")) {
    const key = argv[i].slice(2);
    const next = argv[i + 1];
    if (next && !next.startsWith("--")) {
      flags.set(key, next);
      i += 1;
    } else {
      flags.set(key, "true");
    }
  } else {
    positional.push(argv[i]);
  }
}

const id = positional[0];
if (!id || !/^[a-z0-9]+(-[a-z0-9]+)*$/.test(id)) {
  console.error(
    'Usage: npm run new-reel -- <kebab-id> --name "Title" --beats hook,problem,fix,finale',
  );
  process.exit(1);
}

const pascal = id.replace(/(^|-)([a-z0-9])/g, (_, __, c) => c.toUpperCase());
const camel = pascal[0].toLowerCase() + pascal.slice(1);
const title = flags.get("name") ?? pascal;
const beats = (flags.get("beats") ?? "hook,problem,proof,fix,finale")
  .split(",")
  .map((b) => b.trim())
  .filter(Boolean);
const lineCount = Number(flags.get("lines") ?? beats.length);
const force = flags.has("force");

const templateDir = path.join(root, "src/templates", id);
const exists = await access(templateDir).then(
  () => true,
  () => false,
);
if (exists && !force) {
  console.error(`${path.relative(repoRoot, templateDir)} already exists (use --force)`);
  process.exit(1);
}

const beatPascal = (b) => b.replace(/(^|-)([a-z0-9])/g, (_, __, c) => c.toUpperCase());
const sceneComponent = (b) => `${beatPascal(b)}Scene`;
// Scene lengths default to an even split of 30s on the 0.5s grid the timeline
// comments describe; retiming is a one-number edit per beat afterwards.
const evenLen = Math.round((30 / beats.length) * 2) / 2;
const clipName = (i) => `${String(i + 1).padStart(2, "0")}-${beats[i] ?? `line${i + 1}`}`;
const clips = Array.from({ length: lineCount }, (_, i) => clipName(i));

const files = {};

files["schema.ts"] = `import { z } from "zod";

// The public contract of this reel: what a caller may change without editing
// the template. Brand text belongs here, motion does not.
export const ${camel}Schema = z.object({
  ctaLabel: z.string().describe("Final call-to-action chip text"),
});

export type ${pascal}Props = z.infer<typeof ${camel}Schema>;
`;

files["palette.ts"] = `import { Palette } from "../../theme";

// One hero color, everything else monochrome — max one glowing element per
// frame. Replace these with the scenario's palette.
export const ${camel}Palette: Palette = {
  bg: "#07070A",
  bgAlt: "#101016",
  primary: "#7C3AED", // THE hero color
  accent: "#B49BFF", // tint of the hero, secondary data only
  text: "#F4F4F7",
  textDim: "#8E8E9A",
  glow: "rgba(124, 58, 237, 0.42)",
};

export const ${camel}Colors = {
  surface: "rgba(18, 18, 24, 0.84)",
  surfaceStrong: "#15151B",
  surfaceLift: "#20202A",
  line: "rgba(235, 235, 245, 0.14)",
  lineStrong: "rgba(235, 235, 245, 0.32)",
  white: "#FFFFFF",
  ink: "#08080B",
  dim: "#55555E",
  shadow: "0 30px 80px -46px rgba(0, 0, 0, 0.9)",
} as const;
`;

files["durations.ts"] =
  `// Generated by scripts/gen-voiceover.mjs — do not edit by hand.\n` +
  `// Empty until the voiceover is synthesised:\n` +
  `//   npm run voiceover -- scripts/voiceover/${id}.json\n` +
  `export const DURATIONS = {} as Record<string, number>;\n`;

files["timeline.ts"] = `// The scenario as data. Voiceover only — no music, no SFX — so every cut is
// paced off the spoken lines.
//
// Scene starts are derived from the lengths below; clip durations come from
// the generated durations module. Nothing here is transcribed by hand.
import { buildScenes, defineVoiceover, scenesDuration, VoLine } from "../../reel";
import { DURATIONS } from "./durations";

// Playback rate of the voiceover clips. 1.05–1.10 tightens the read without
// pitching the voice audibly.
export const VO_RATE = 1.06;

export const SCENES = buildScenes({
${beats.map((b) => `  ${b}: ${evenLen}, // TODO: what the viewer sees in this beat`).join("\n")}
});

export const DURATION = scenesDuration(SCENES);

export type { VoLine };

// "~PAGE" hides a page (a headline carries those words), "+WORD" paints it
// the hero color once spoken, "!WORD" the signal color.
export const VOICEOVER = defineVoiceover(DURATIONS, [
${clips
  .map(
    (c, i) => `  {
    file: "${c}",
    start: ${(i * evenLen).toFixed(2)},
    pages: ["TODO CAPTION", "PAGES FOR THIS LINE"],
  },`,
  )
  .join("\n")}
]);
`;

files["ui.tsx"] = `// Scene primitives for this reel. Keep them here rather than in the scenes
// so the visual language stays consistent across cuts.
import React from "react";
import { interpolate, spring, useCurrentFrame, useVideoConfig } from "remotion";
import { theme } from "../../theme";
import { ${camel}Palette } from "./palette";

// Entrances animate opacity + translateY + scale together — never a lone fade.
export const Headline: React.FC<{
  children: React.ReactNode;
  delay?: number;
  size?: number;
}> = ({ children, delay = 0, size = 118 }) => {
  const frame = useCurrentFrame();
  const { fps } = useVideoConfig();
  const p = spring({ frame: frame - delay, fps, config: theme.spring.smooth });
  return (
    <div
      style={{
        fontFamily: theme.fonts.display,
        fontSize: size,
        fontWeight: 800,
        letterSpacing: "-0.035em",
        lineHeight: 0.95,
        color: ${camel}Palette.text,
        textAlign: "center",
        opacity: p,
        transform: \`translateY(\${interpolate(p, [0, 1], [40, 0])}px) scale(\${interpolate(
          p,
          [0, 1],
          [0.92, 1],
        )})\`,
      }}
    >
      {children}
    </div>
  );
};
`;

files[`${pascal}.tsx`] = `import React from "react";
import { Reel, Scene } from "../../reel";
import { ${camel}Palette } from "./palette";
import { ${pascal}Props } from "./schema";
import { SCENES, VOICEOVER, VO_RATE } from "./timeline";
${beats.map((b) => `import { ${sceneComponent(b)} } from "./scenes/${sceneComponent(b)}";`).join("\n")}

export const ${pascal}: React.FC<${pascal}Props> = ({ ctaLabel }) => (
  <Reel
    palette={${camel}Palette}
    voiceoverDir="${id}"
    voiceover={VOICEOVER}
    voRate={VO_RATE}
    captions={{ activeColor: ${camel}Palette.primary }}
  >
${beats
  .map(
    (b, i) => `    <Scene spec={SCENES.${b}} name="${String(i + 1).padStart(2, "0")} ${b}">
      <${sceneComponent(b)}${b === beats[beats.length - 1] ? " ctaLabel={ctaLabel}" : ""} />
    </Scene>`,
  )
  .join("\n")}
  </Reel>
);
`;

files["index.ts"] = `import { defineTemplate } from "../types";
import { ${pascal} } from "./${pascal}";
import { ${camel}Schema } from "./schema";
import { DURATION } from "./timeline";

export const ${camel} = defineTemplate({
  id: "${id}",
  name: "${title}",
  description: "TODO: one line — what the viewer sees and what it sells.",
  schema: ${camel}Schema,
  defaultProps: {
    ctaLabel: "LEARN MORE",
  },
  durationInSeconds: DURATION,
  formats: ["reel"],
  component: ${pascal},
});
`;

for (const [i, beat] of beats.entries()) {
  const isLast = i === beats.length - 1;
  files[`scenes/${sceneComponent(beat)}.tsx`] = `import React from "react";
import { AbsoluteFill } from "remotion";
import { BgMesh } from "../../../components/Layers";
import { ${camel}Palette } from "../palette";
import { Headline } from "../ui";

// TODO: the "${beat}" beat.
export const ${sceneComponent(beat)}: React.FC${isLast ? "<{ ctaLabel: string }>" : ""} = (${isLast ? "{ ctaLabel }" : ""}) => (
  <AbsoluteFill>
    <BgMesh palette={${camel}Palette} />
    <AbsoluteFill style={{ alignItems: "center", justifyContent: "center" }}>
      <Headline>${isLast ? "{ctaLabel}" : beat.toUpperCase()}</Headline>
    </AbsoluteFill>
  </AbsoluteFill>
);
`;
}

for (const [rel, content] of Object.entries(files)) {
  const target = path.join(templateDir, rel);
  await mkdir(path.dirname(target), { recursive: true });
  await writeFile(target, content);
}

// Voiceover manifest — the author's voice by env reference, never picked from
// the ElevenLabs list.
const manifestPath = path.join(root, "scripts/voiceover", `${id}.json`);
await writeFile(
  manifestPath,
  `${JSON.stringify(
    {
      voiceId: VOICE_REF,
      outDir: `public/voiceover/${id}`,
      modelId: "eleven_multilingual_v2",
      voiceSettings: {
        stability: 0.48,
        similarity_boost: 0.82,
        style: 0.28,
        use_speaker_boost: true,
      },
      lines: clips.map((c) => [c, "TODO: the spoken line."]),
    },
    null,
    2,
  )}\n`,
);

// Scenario file — the brief this reel was built from, kept beside the code.
const scenarioPath = path.join(root, "scripts/scenarios", `${id}.md`);
await mkdir(path.dirname(scenarioPath), { recursive: true });
const scenarioExists = await access(scenarioPath).then(
  () => true,
  () => false,
);
if (!scenarioExists) {
  await writeFile(
    scenarioPath,
    `# ${title}

- **id**: ${id}
- **format**: reel (1080×1920), ~30s
- **series**: standalone | «ДЕНЬГИ · ПРОСТО» ВЫПУСК NN (kit re-exported from <prev>)
- **hero color**: TODO
- **hook (first 2s)**: TODO — what stops the scroll
- **face**: none | face-led hook 0–5s | corner PiP on beats …

## Beats

${beats
  .map(
    (b, i) =>
      `${i + 1}. **${b}** — TODO: what the viewer sees.\n` +
      `   - улика: none | what proves this line, and in which container (paper / screen / studio)`,
  )
  .join("\n")}

## Voiceover

${clips.map((c) => `- \`${c}\`: TODO spoken line.`).join("\n")}

## Presenter

Only if **face** is not "none" — otherwise delete this section.

- character: \${HEYGEN_AVATAR_VIEW_ID} (photo, studio) | Digital Twin
- shots: which beats, which lines — full-screen by default; corner circle only on request
- agreed price: $0.xx on avatar_iv — quoted from --dry-run, confirmed by user

## CTA

TODO

## Deviations

- What changed against the brief and why: hook rewritten, beats merged or
  split, duration vs the brief's clock, music/SFX cues carried visually.
`,
  );
}

// Registry — idempotent insert so re-scaffolding never duplicates the entry.
const registryPath = path.join(root, "src/templates/index.ts");
const registry = await readFile(registryPath, "utf8");
if (!registry.includes(`from "./${id}"`)) {
  const withImport = registry.replace(
    /\n\nexport const templates/,
    `\nimport { ${camel} } from "./${id}";\n\nexport const templates`,
  );
  const withEntry = withImport.replace(/\n\];\n?$/, `\n  ${camel},\n];\n`);
  await writeFile(registryPath, withEntry);
}

const rel = (p) => path.relative(repoRoot, p);
console.log(`Scaffolded ${id}:
  ${rel(templateDir)}/  (schema, palette, timeline, ui, ${beats.length} scenes)
  ${rel(scenarioPath)}
  ${rel(manifestPath)}
  registered in ${rel(registryPath)}

Next:
  1. Write the scenario in ${rel(scenarioPath)}, then the spoken lines into the manifest.
  2. npm run voiceover -- scripts/voiceover/${id}.json     (mp3s + durations.ts)
  3. Set scene lengths and caption pages in ${rel(path.join(templateDir, "timeline.ts"))}.
  4. Build the scenes, then verify:
     npm run stills -- ${id}-reel
     npm run render -- ${id}-reel --out out/${id}-reel.mp4`);
