// Generated by scripts/gen-voiceover.mjs — do not edit by hand.
// Measured mp3 durations in seconds, before VO_RATE playback scaling.
// Regenerate: npm run voiceover -- scripts/voiceover/digital-ruble.json --durations-only
export const DURATIONS = {
  "01-hook": 7.152,
  "02-stop": 5.062,
  "03-forms": 8.916,
  "04-parity": 3.669,
  "05-launch": 10.495,
  "06-voluntary": 6.316,
  "07-pros": 7.941,
  "08-cons": 6.269,
  "09-question": 8.452,
  "10-cta": 8.127,
} as const;
