// Generated by scripts/gen-voiceover.mjs — do not edit by hand.
// Measured mp3 durations in seconds, before VO_RATE playback scaling.
// Regenerate: npm run voiceover -- scripts/voiceover/no-it-in-russia.json --durations-only
export const DURATIONS = {
  "01-hook": 5.108,
  "02-numbers": 5.759,
  "03-break": 3.065,
  "04-economy": 7.152,
  "05-tasks": 7.477,
  "06-insight": 8.452,
  "07-junior": 7.57,
  "08-factcheck": 6.362,
  "09-answer": 5.341,
  "10-cta": 3.622,
} as const;
