// Generated by scripts/gen-voiceover.mjs — do not edit by hand.
// Measured mp3 durations in seconds, before VO_RATE playback scaling.
// Regenerate: npm run voiceover -- scripts/voiceover/mrbeast-100k.json --durations-only
export const DURATIONS = {
  "01-hook": 2.972,
  "02-count": 4.087,
  "03-stamp": 5.016,
  "04-thumbnail": 3.437,
  "05-formula": 6.594,
  "06-timeline": 6.316,
  "07-lesson": 5.294,
  "08-yoloco": 4.273,
} as const;
