// Generated by scripts/gen-voiceover.mjs — do not edit by hand.
// Measured mp3 durations in seconds, before VO_RATE playback scaling.
// Regenerate: npm run voiceover -- scripts/voiceover/race-condition.json --durations-only
export const DURATIONS = {
  "01-hook": 4.133,
  "02-read": 3.111,
  "03-sold": 3.762,
  "04-race": 4.876,
  "05-lock": 6.548,
  "06-law": 3.529,
} as const;
