// Generated by scripts/gen-voiceover.mjs — do not edit by hand.
// Measured mp3 durations in seconds, before VO_RATE playback scaling.
// Regenerate: npm run voiceover -- scripts/voiceover/ai-influencer.json --durations-only
export const DURATIONS = {
  "01-hook": 4.458,
  "02-ai": 5.341,
  "03-brands": 5.294,
  "04-trust": 4.69,
  "05-believe": 4.551,
  "06-question": 3.437,
} as const;
