// Generated by scripts/gen-voiceover.mjs — do not edit by hand.
// Measured mp3 durations in seconds, before VO_RATE playback scaling.
// Regenerate: npm run voiceover -- scripts/voiceover/yoclips-promo.json --durations-only
export const DURATIONS = {
  "01-hook": 4.923,
  "02-brief": 3.39,
  "03-scenario": 7.152,
  "04-budget": 6.223,
  "05-voice": 5.759,
  "06-render": 5.016,
  "07-keys": 5.062,
  "08-scale": 6.409,
  "09-cta": 3.019,
} as const;
