// Generated by scripts/gen-footage.mjs — do not edit by hand.
// Measured after the cut, not copied from the config: the config asks for a
// range, ffmpeg delivers whole frames, and the two differ by up to one frame.
// Regenerate: node scripts/gen-footage.mjs scripts/footage/yoclips-promo.json
export const FOOTAGE = {
  "02-brief": { seconds: 4.8, width: 1080, height: 1678 }, // тема + бриф печатаются в форме «НОВЫЙ РОЛИК»
  "03-scenario": { seconds: 4, width: 1080, height: 1678 }, // таблица битов сценария на чеке
  "04-budget": { seconds: 5, width: 1080, height: 1678 }, // смета: движки, строки, ИТОГО ДЕНЬГАМИ $0.25
  "05-voice": { seconds: 4, width: 1080, height: 1678 }, // сетка фото-образов ведущего + двойник
  "06-render": { seconds: 4, width: 1080, height: 1678 }, // готовые поля YouTube: заголовок, описание, теги, первый комментарий
  "07-keys": { seconds: 3.8, width: 1080, height: 1678 }, // ключ владельца в мастере настройки, «Ваши данные надёжно защищены»
} as const;

/** Every clip is cut to this rate; a scene may assume it. */
export const FOOTAGE_FPS = 30;

export type FootageShot = keyof typeof FOOTAGE;
